### ISSUE TITLE
pihole -g needs to be run when indendent mode is on, otherwise nothing is blocked.

### ISSUE THREAD

**Issue by AmandaCameron** [r-pufky/ansible_pihole#24]
I see in https://github.com/r-pufky/ansible_pihole/blob/main/tasks/db/db.yml#L67-L69 that `pihole -g` isn't run unless the pihole install is fresh, however idempotent mode blows away the database, and thus the adlist contents on every run, so it needs to be run in those cases as well.

**Comment by r-pufky** [comment]
Thanks for the report. I’ll look into it when I get some time (probably
later tonight).

I seem to recall when idempotent is turned on, the install process itself
should take care of regenerating the gravity databases; but will confirm
what is going on.

**Comment by r-pufky** [comment]
Confirmed this is an issue in the case where pihole is already installed,  and `pihole_update_enable` is `false` and `pihole_idempotent` is `true`.
